version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=tabeldata_auth
      - POSTGRES_USER=tabeldata_auth
      - POSTGRES_DB=tabeldata_auth
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-server-network
  springboot:
    image: tabeldata-oauth2-auth-server:1.0.3-release
    environment:
      - APPLICATION_PORT=8080
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=tabeldata_auth
      - DATABASE_USER=tabeldata_auth
      - DATABASE_PASSWORD=tabeldata_auth
    entrypoint:
      - "java"
      - '-jar'
      - "-Djava.security.egd=file:/dev/./urandom"
      - "/var/applications/application.jar"
    networks:
      - auth-server-network
    depends_on:
      - postgres
volumes:
  postgres_data:
networks:
  auth-server-network:
